// Flat ESLint config scoped to one job: catch hardcoded user-facing strings so
// every visible string flows through i18n. Deliberately narrow — it does NOT
// enable broad rulesets, to avoid flagging pre-existing patterns elsewhere.
//
// react-hooks and @typescript-eslint are registered (but their rules left off)
// only so the project's existing inline `eslint-disable` directives for those
// rules resolve instead of erroring.
import i18next from "eslint-plugin-i18next";
import reactHooks from "eslint-plugin-react-hooks";
import tseslint from "typescript-eslint";

export default [
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "src/ipc/bindings.ts", // generated by tauri-specta
      "src/locales/**",
      "src/**/*.{test,spec}.{ts,tsx}", // tests legitimately use literal strings
    ],
  },
  {
    files: ["src/**/*.{ts,tsx}"],
    // The project's existing react-hooks / no-explicit-any disable directives are
    // dormant here (we don't run those rules), so don't report them as unused.
    linterOptions: { reportUnusedDisableDirectives: "off" },
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    plugins: {
      i18next,
      "react-hooks": reactHooks,
      "@typescript-eslint": tseslint.plugin,
    },
    rules: {
      "i18next/no-literal-string": [
        "error",
        {
          mode: "jsx-only",
          // Only flag user-facing attributes; ignore className/value/role/etc.
          "jsx-attributes": {
            include: ["placeholder", "title", "aria-label", "alt"],
          },
        },
      ],
    },
  },
];
