// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Returns app/build info from the core. Works without a vault open. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**
	 *  Which platform this shell was built for. The frontend adapts vault
	 *  onboarding: mobile has no folder picker — the vault lives app-private and
	 *  is populated via the git adoption path (MOBILE.md).
	 */
	platformInfo: () => __TAURI_INVOKE<string>("platform_info"),
	/**
	 *  The app-private default vault location used by mobile onboarding. Works
	 *  without a vault open. Creates the directory so the returned path passes
	 *  the store's validate-before-open check on first use.
	 */
	defaultVaultPath: () => typedError<string, CommandError>(__TAURI_INVOKE("default_vault_path")),
	/**
	 *  Open (or create) a vault at `path`.
	 * 
	 *  `async` + `spawn_blocking`: indexing reads every note, and a vault on a
	 *  cloud-synced folder (OneDrive/iCloud) hydrates online-only files over the
	 *  network — slow and blocking. A synchronous command runs on the main thread,
	 *  so that work would freeze the UI; running it on a blocking-pool thread keeps
	 *  the window responsive (it shows the loading state) while indexing proceeds.
	 */
	openVault: (path: string) => typedError<VaultInfo, CommandError>(__TAURI_INVOKE("open_vault", { path })),
	/**  Close the current vault (drops the index connection). */
	closeVault: () => typedError<null, CommandError>(__TAURI_INVOKE("close_vault")),
	/**  Path of the currently open vault, if any. */
	currentVault: () => typedError<string | null, CommandError>(__TAURI_INVOKE("current_vault")),
	/**
	 *  Show a native folder picker; returns the chosen path, if any.
	 * 
	 *  Must be `async`: a synchronous command runs on the main thread, and
	 *  `blocking_pick_folder` would then deadlock — it asks the main thread's event
	 *  loop to show the native panel while blocking that same thread. Running the
	 *  blocking call on a blocking-pool thread keeps the main thread free to render
	 *  the panel.
	 */
	pickVaultFolder: () => __TAURI_INVOKE<string | null>("pick_vault_folder"),
	/**
	 *  Validate a candidate vault path *without* opening it or touching the engine
	 *  lock. Returns summary info for an existing directory; errors if the path is
	 *  missing or not a directory. Used to preview recent vaults and detect ones
	 *  whose folder was moved/deleted before the user switches to them.
	 */
	validateVault: (path: string) => typedError<VaultInfo, CommandError>(__TAURI_INVOKE("validate_vault", { path })),
	/**  The recent-vaults list (most-recent first) for quick switching. */
	listRecentVaults: () => typedError<RecentVault[], CommandError>(__TAURI_INVOKE("list_recent_vaults")),
	/**  Drop a stale entry (moved/deleted folder) from the recent-vaults list. */
	removeRecentVault: (path: string) => typedError<null, CommandError>(__TAURI_INVOKE("remove_recent_vault", { path })),
	listNotes: () => typedError<NoteSummary[], CommandError>(__TAURI_INVOKE("list_notes")),
	/**
	 *  `async` + `spawn_blocking`: reading a note on a OneDrive/iCloud vault may
	 *  hydrate an online-only file over the network. Off the main thread, that read
	 *  never blocks the UI or other commands (the frontend masks it with a loading
	 *  state and prefetch-on-hover).
	 */
	getNote: (path: string) => typedError<Note, CommandError>(__TAURI_INVOKE("get_note", { path })),
	/**
	 *  `async` + `spawn_blocking`: resolving an `![[embed]]` reads the target note
	 *  from disk, which on a OneDrive/iCloud vault may hydrate an online-only file
	 *  over the network — so it runs off the main thread like [`get_note`]. Never
	 *  creates a note on a miss; returns `EmbedResolution { kind: missing }`.
	 */
	resolveEmbed: (target: string) => typedError<EmbedResolution, CommandError>(__TAURI_INVOKE("resolve_embed", { target })),
	createNote: (req: CreateNoteRequest) => typedError<Note, CommandError>(__TAURI_INVOKE("create_note", { req })),
	updateNote: (path: string, content: string) => typedError<Note, CommandError>(__TAURI_INVOKE("update_note", { path, content })),
	updateNoteMeta: (req: UpdateMetaRequest) => typedError<Note, CommandError>(__TAURI_INVOKE("update_note_meta", { req })),
	setProperty: (path: string, key: string, value: PropertyValue) => typedError<Note, CommandError>(__TAURI_INVOKE("set_property", { path, key, value })),
	removeProperty: (path: string, key: string) => typedError<Note, CommandError>(__TAURI_INVOKE("remove_property", { path, key })),
	renameProperty: (path: string, from: string, to: string) => typedError<Note, CommandError>(__TAURI_INVOKE("rename_property", { path, from, to })),
	moveNote: (path: string, newPath: string) => typedError<Note, CommandError>(__TAURI_INVOKE("move_note", { path, newPath })),
	duplicateNote: (path: string) => typedError<Note, CommandError>(__TAURI_INVOKE("duplicate_note", { path })),
	deleteNote: (path: string) => typedError<null, CommandError>(__TAURI_INVOKE("delete_note", { path })),
	/**  List every `.canvas` file in the vault. */
	listCanvases: () => typedError<CanvasFile[], CommandError>(__TAURI_INVOKE("list_canvases")),
	/**  Read a canvas file's raw JSON content. */
	readCanvas: (path: string) => typedError<string, CommandError>(__TAURI_INVOKE("read_canvas", { path })),
	/**  Overwrite an existing canvas file atomically. */
	writeCanvas: (path: string, content: string) => typedError<null, CommandError>(__TAURI_INVOKE("write_canvas", { path, content })),
	/**  Create a new canvas file with initial JSON content. */
	createCanvas: (path: string, content: string) => typedError<CanvasFile, CommandError>(__TAURI_INVOKE("create_canvas", { path, content })),
	/**  Permanently delete a canvas file. */
	deleteCanvas: (path: string) => typedError<null, CommandError>(__TAURI_INVOKE("delete_canvas", { path })),
	/**
	 *  Reveal a note file or folder in the OS file manager (Finder/Explorer/file
	 *  manager), selecting the item. `path` is vault-relative (forward-slashed); an
	 *  empty string reveals the vault root. If the target no longer exists (e.g. a
	 *  brand-new note not yet flushed to disk), falls back to revealing its parent.
	 */
	revealInFileManager: (path: string) => typedError<null, CommandError>(__TAURI_INVOKE("reveal_in_file_manager", { path })),
	resolveOrCreateWikiLink: (title: string) => typedError<string, CommandError>(__TAURI_INVOKE("resolve_or_create_wiki_link", { title })),
	getFolderTree: () => typedError<FolderNode, CommandError>(__TAURI_INVOKE("get_folder_tree")),
	createFolder: (path: string) => typedError<null, CommandError>(__TAURI_INVOKE("create_folder", { path })),
	deleteFolder: (path: string) => typedError<null, CommandError>(__TAURI_INVOKE("delete_folder", { path })),
	/**
	 *  Delete a folder and all its contents by moving the whole subtree to trash.
	 *  Unlike [`delete_folder`] (which only removes an empty folder), this is
	 *  recoverable. The index is rebuilt so the removed notes leave it immediately.
	 * 
	 *  `async` + `spawn_blocking` for the same reason as [`reindex_vault`]: the
	 *  full index rebuild reads every note and would freeze the UI on the main
	 *  thread.
	 */
	deleteFolderRecursive: (path: string) => typedError<null, CommandError>(__TAURI_INVOKE("delete_folder_recursive", { path })),
	/**
	 *  Notes move with the folder; rebuild the index so paths stay correct even
	 *  before the file watcher catches up.
	 * 
	 *  `async` + `spawn_blocking` for the same reason as [`reindex_vault`]: the
	 *  full index rebuild reads every note and would freeze the UI on the main
	 *  thread.
	 */
	moveFolder: (path: string, newPath: string) => typedError<null, CommandError>(__TAURI_INVOKE("move_folder", { path, newPath })),
	search: (query: string, folder: string | null, tag: string | null) => typedError<SearchResult[], CommandError>(__TAURI_INVOKE("search", { query, folder, tag })),
	quickSearch: (query: string) => typedError<NoteSummary[], CommandError>(__TAURI_INVOKE("quick_search", { query })),
	/**  Distinct note tags with per-tag note counts, for the tag browser/autocomplete. */
	listTags: () => typedError<TagCount[], CommandError>(__TAURI_INVOKE("list_tags")),
	/**
	 *  Notes linking to `title`, each with the snippet line(s) where they do.
	 * 
	 *  `async` + `spawn_blocking`: this reads candidate note bodies to extract the
	 *  context snippet, which on a OneDrive/iCloud vault could hydrate a file over
	 *  the network. Off the main thread, that never freezes the UI (online-only
	 *  placeholders are skipped in the core, so they don't block at all).
	 */
	backlinks: (title: string) => typedError<LinkReference[], CommandError>(__TAURI_INVOKE("backlinks", { title })),
	/**
	 *  Notes that name `title` without linking it, each with the bare-mention line(s).
	 *  `async` + `spawn_blocking` for the same reason as [`backlinks`].
	 */
	unlinkedMentions: (title: string, selfPath: string) => typedError<LinkReference[], CommandError>(__TAURI_INVOKE("unlinked_mentions", { title, selfPath })),
	/**
	 *  Turn the first bare mention of `title` on `line` of `path` into a `[[title]]`
	 *  wikilink (then re-index). Returns the updated note.
	 */
	linkMention: (path: string, title: string, line: number) => typedError<Note, CommandError>(__TAURI_INVOKE("link_mention", { path, title, line })),
	/**  The 1-hop link neighborhood of `path` for the local graph view. Index-only. */
	noteGraph: (path: string) => typedError<NoteGraph, CommandError>(__TAURI_INVOKE("note_graph", { path })),
	/**
	 *  The whole-vault link graph for the Graph view. Index-only — never reads
	 *  note bodies (no cloud hydration on graph open).
	 */
	fullGraph: () => typedError<FullGraph, CommandError>(__TAURI_INVOKE("full_graph")),
	/**
	 *  Tagged blocks whose text matches `query`, for the `((` reference
	 *  autocomplete. Index-only (no disk reads).
	 */
	searchBlocks: (query: string) => typedError<BlockHit[], CommandError>(__TAURI_INVOKE("search_blocks", { query })),
	/**
	 *  Resolve a `((^id))` block reference to its note + text, straight from the
	 *  index. `found: false` for a dangling id — never errors, never creates.
	 */
	resolveBlock: (blockId: string) => typedError<BlockResolution, CommandError>(__TAURI_INVOKE("resolve_block", { blockId })),
	/**
	 *  Notes that reference the block `block_id` via `((^id))`, with the line(s)
	 *  where the reference appears (block-level backlinks).
	 * 
	 *  `async` + `spawn_blocking` for the same reason as [`backlinks`]: it reads
	 *  candidate note bodies to extract the context snippet.
	 */
	blockBacklinks: (blockId: string) => typedError<LinkReference[], CommandError>(__TAURI_INVOKE("block_backlinks", { blockId })),
	/**  The indexed frontmatter properties of `path`, typed. Index-only. */
	noteProperties: (path: string) => typedError<NotePropertyEntry[], CommandError>(__TAURI_INVOKE("note_properties", { path })),
	/**
	 *  The typed relations of `path` in both directions: the notes its frontmatter
	 *  points to (`outgoing`) and the notes pointing to it (`incoming`,
	 *  reciprocal). Index-only.
	 */
	noteRelations: (path: string) => typedError<NoteRelations, CommandError>(__TAURI_INVOKE("note_relations", { path })),
	/**
	 *  Roll up a numeric `property_key` over the notes `path` relates to via
	 *  `relation_key` (count/sum/avg/min/max). Index-only.
	 */
	noteRollup: (path: string, relationKey: string, propertyKey: string, op: RollupOp) => typedError<RollupResult, CommandError>(__TAURI_INVOKE("note_rollup", { path, relationKey, propertyKey, op })),
	/**
	 *  Run a query-DSL string against the index and return matched notes (plus the
	 *  tasks of those notes when the query touches tasks), for the query view's
	 *  table / kanban / calendar renderers.
	 * 
	 *  `async`: the index read runs on a blocking thread (off the UI), and a
	 *  `sort:similarity:"phrase"` clause additionally embeds the phrase and re-ranks
	 *  the results via the semantic index — that path errors loudly if no embedding
	 *  model is configured (see [`crate::ai::commands::similarity_scores`]).
	 */
	runQuery: (query: string) => typedError<QueryResult, CommandError>(__TAURI_INVOKE("run_query", { query })),
	getVaultInfo: () => typedError<VaultInfo, CommandError>(__TAURI_INVOKE("get_vault_info")),
	getVaultStats: () => typedError<VaultStats, CommandError>(__TAURI_INVOKE("get_vault_stats")),
	/**
	 *  Rebuild the entire index from the vault. Returns the number of notes indexed.
	 * 
	 *  `async` + `spawn_blocking` for the same reason as [`open_vault`]: a full
	 *  rebuild reads every note and would freeze the UI if run on the main thread.
	 */
	reindexVault: () => typedError<number, CommandError>(__TAURI_INVOKE("reindex_vault")),
	/**
	 *  Re-scan from disk (pull model — used on mobile/foreground and manual refresh).
	 *  For M1 this is a full rebuild; incremental mtime scanning comes later.
	 */
	rescanVault: () => typedError<number, CommandError>(__TAURI_INVOKE("rescan_vault")),
	listConflicts: () => typedError<ConflictFile[], CommandError>(__TAURI_INVOKE("list_conflicts")),
	conflictDiff: (original: string, conflict: string) => typedError<ConflictDiff, CommandError>(__TAURI_INVOKE("conflict_diff", { original, conflict })),
	resolveConflict: (req: ResolveConflictRequest) => typedError<string | null, CommandError>(__TAURI_INVOKE("resolve_conflict", { req })),
	listTrash: () => typedError<TrashItem[], CommandError>(__TAURI_INVOKE("list_trash")),
	restoreTrash: (id: string) => typedError<string, CommandError>(__TAURI_INVOKE("restore_trash", { id })),
	deleteTrashItem: (id: string) => typedError<null, CommandError>(__TAURI_INVOKE("delete_trash_item", { id })),
	emptyTrash: () => typedError<number, CommandError>(__TAURI_INVOKE("empty_trash")),
	listVersions: (path: string) => typedError<VersionMeta[], CommandError>(__TAURI_INVOKE("list_versions", { path })),
	readVersion: (path: string, versionId: string) => typedError<string, CommandError>(__TAURI_INVOKE("read_version", { path, versionId })),
	/**  Line-diff a snapshot against the current note ("what changed since this version"). */
	diffVersion: (path: string, versionId: string) => typedError<DiffLine[], CommandError>(__TAURI_INVOKE("diff_version", { path, versionId })),
	restoreVersion: (path: string, versionId: string) => typedError<Note, CommandError>(__TAURI_INVOKE("restore_version", { path, versionId })),
	getPreferences: () => typedError<Preferences, CommandError>(__TAURI_INVOKE("get_preferences")),
	setPreferences: (prefs: Preferences) => typedError<null, CommandError>(__TAURI_INVOKE("set_preferences", { prefs })),
	/**
	 *  Local repository status of the open vault. Works without a repo —
	 *  `initialized: false` means git sync isn't set up yet, not an error.
	 *  `async` + `spawn_blocking`: the status scan walks the working tree.
	 */
	gitStatus: () => typedError<GitStatus, CommandError>(__TAURI_INVOKE("git_status")),
	/**
	 *  Initialize the vault repository if needed and commit everything pending
	 *  with the configured author. Serves both the enable toggle (baseline
	 *  commit) and the manual "commit now" button; the background auto-committer
	 *  runs the same core path. `async` + `spawn_blocking` with the engine lock
	 *  released: the baseline commit hashes EVERY file in the vault — on the
	 *  main thread or under the lock it would freeze the app for its duration.
	 */
	gitCommitNow: () => typedError<GitStatus, CommandError>(__TAURI_INVOKE("git_commit_now")),
	/**
	 *  Commit everything pending and return the resulting HEAD commit id — a
	 *  checkpoint a later [`git_reset_hard`] can revert to (e.g. before/after an
	 *  agentic editing session). Returns `None` if the vault isn't a repo.
	 */
	gitCheckpoint: () => typedError<string | null, CommandError>(__TAURI_INVOKE("git_checkpoint")),
	/**
	 *  Hard-reset the vault to `commit_id`, discarding all later changes — the
	 *  "undo this AI session" primitive. Irreversible by design; the caller
	 *  confirms first.
	 */
	gitResetHard: (commitId: string) => typedError<GitStatus, CommandError>(__TAURI_INVOKE("git_reset_hard", { commitId })),
	/**
	 *  Set or clear the vault's `origin` remote. HTTPS only — this build
	 *  deliberately ships no ssh transport (engine-spike sign-off).
	 */
	gitSetRemote: (url: string | null) => typedError<GitStatus, CommandError>(__TAURI_INVOKE("git_set_remote", { url })),
	/**
	 *  Store (or, with an empty string, remove) the vault's git access token in
	 *  secret storage.
	 */
	gitSetToken: (token: string) => typedError<null, CommandError>(__TAURI_INVOKE("git_set_token", { token })),
	/**
	 *  Whether a git access token is stored for this vault (the UI shows state
	 *  without ever receiving the token).
	 */
	gitHasToken: () => typedError<boolean, CommandError>(__TAURI_INVOKE("git_has_token")),
	/**
	 *  One manual sync cycle: fetch, then fast-forward, push, or auto-merge
	 *  (P2b — merge conflicts stop and are surfaced with their paths; never a
	 *  force-push). A file-changing checkout (pull or merge) is adopted the
	 *  same way for both: the watcher reindexes the checked-out paths and the
	 *  frontend reloads open notes via the external-change guard. `async` +
	 *  `spawn_blocking` off the engine lock: network plus checkout work.
	 */
	gitSyncNow: () => typedError<GitSyncOutcome, CommandError>(__TAURI_INVOKE("git_sync_now")),
	/**
	 *  The conflicted paths of a diverged merge with base/ours/theirs
	 *  materialized (P3a). Stateless: re-derived in memory on every call —
	 *  nothing is persisted between sync's `Conflicted` outcome and resolution,
	 *  so a restart just re-opens the resolver from this list. `async` +
	 *  `spawn_blocking` off the engine lock: the merge hashes blobs.
	 */
	gitMergeConflicts: () => typedError<GitConflict[], CommandError>(__TAURI_INVOKE("git_merge_conflicts")),
	/**
	 *  Complete a conflicted merge with one resolution per conflicted path
	 *  (P3a): fetch, re-derive, apply, then 2-parent commit + checkout + push.
	 *  The checkout writes the merged files; the watcher reindexes them and the
	 *  frontend reloads open notes via the external-change path — the same
	 *  adoption as a pull. `async` + `spawn_blocking` off the engine lock:
	 *  network plus checkout work (mirrors `git_sync_now`).
	 */
	gitFinalizeMerge: (resolutions: GitResolution[]) => typedError<null, CommandError>(__TAURI_INVOKE("git_finalize_merge", { resolutions })),
	listTasks: (query: TaskQuery) => typedError<Task[], CommandError>(__TAURI_INVOKE("list_tasks", { query })),
	createTask: (req: CreateTaskRequest) => typedError<Task, CommandError>(__TAURI_INVOKE("create_task", { req })),
	toggleTask: (id: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("toggle_task", { id })),
	setTaskStatus: (id: string, status: string) => typedError<null, CommandError>(__TAURI_INVOKE("set_task_status", { id, status })),
	/**
	 *  Set or clear an annotation on a task. `field` is one of `project` | `epic` |
	 *  `priority` | `due`; `value = null` removes it.
	 */
	updateTask: (id: string, field: string, value: string | null) => typedError<null, CommandError>(__TAURI_INVOKE("update_task", { id, field, value })),
	/**  Delete a task (remove its checkbox line from the source note). */
	deleteTask: (id: string) => typedError<null, CommandError>(__TAURI_INVOKE("delete_task", { id })),
	/**
	 *  Move a task (and its subtask block) to another note. The task id changes
	 *  after the move (id = hash of path + line); the frontend reloads.
	 */
	moveTask: (id: string, destNote: string) => typedError<null, CommandError>(__TAURI_INVOKE("move_task", { id, destNote })),
	quickCapture: (req: CaptureRequest) => typedError<string, CommandError>(__TAURI_INVOKE("quick_capture", { req })),
	/**
	 *  Export a note to HTML or DOCX, prompting for a save location. Returns the
	 *  saved path, or `None` if the user cancelled.
	 */
	exportNote: (path: string, format: string) => typedError<string | null, CommandError>(__TAURI_INVOKE("export_note", { path, format })),
	listTemplates: () => typedError<NoteTemplate[], CommandError>(__TAURI_INVOKE("list_templates")),
	createTemplate: (name: string, description: string | null, content: string) => typedError<NoteTemplate, CommandError>(__TAURI_INVOKE("create_template", { name, description, content })),
	deleteTemplate: (id: string) => typedError<null, CommandError>(__TAURI_INVOKE("delete_template", { id })),
	/**
	 *  Render a template body's `{{...}}` variables (for inserting into the open
	 *  note). Pure — shares the exact substitution used on the create-note path.
	 */
	renderTemplate: (content: string, title: string | null) => __TAURI_INVOKE<string>("render_template", { content, title }),
	/**
	 *  Save a pasted/dropped image into the vault `media/` folder; returns the
	 *  vault-relative path for embedding as `![](...)`.
	 */
	savePastedImage: (bytes: number[], ext: string) => typedError<string, CommandError>(__TAURI_INVOKE("save_pasted_image", { bytes, ext })),
	listEvents: (rangeStart: string, rangeEnd: string) => typedError<CalendarEvent[], CommandError>(__TAURI_INVOKE("list_events", { rangeStart, rangeEnd })),
	createEvent: (input: EventInput) => typedError<CalendarEvent, CommandError>(__TAURI_INVOKE("create_event", { input })),
	updateEvent: (input: EventInput) => typedError<CalendarEvent, CommandError>(__TAURI_INVOKE("update_event", { input })),
	deleteEvent: (notePath: string) => typedError<null, CommandError>(__TAURI_INVOKE("delete_event", { notePath })),
	getAgenda: (rangeStart: string, rangeEnd: string) => typedError<AgendaItem[], CommandError>(__TAURI_INVOKE("get_agenda", { rangeStart, rangeEnd })),
	/**
	 *  Materialize a meeting note for an own event (feature W1.3): append a dated,
	 *  backlinked entry to the day's journal note and a dated backlink to each
	 *  attendee note. `note_path` is the event's own-note (attendees come from its
	 *  frontmatter — the events index has no attendees column). `date` is the
	 *  occurrence the user acted on (`YYYY-MM-DD`). Idempotent per event+date.
	 */
	addMeetingNote: (notePath: string, date: string) => typedError<MeetingNoteResult, CommandError>(__TAURI_INVOKE("add_meeting_note", { notePath, date })),
	/**
	 *  Assemble the deterministic weekly-review digest for a window. `range_start`
	 *  (inclusive) and `range_end` (exclusive) are offset-carrying RFC 3339 instants
	 *  computed by the frontend in the user's local timezone — see
	 *  [`novalis_core::review`] for the window contract. Read-only; no LLM.
	 */
	reviewDigest: (rangeStart: string, rangeEnd: string) => typedError<ReviewDigest, CommandError>(__TAURI_INVOKE("review_digest", { rangeStart, rangeEnd })),
	listCalendarSources: () => typedError<CalendarSourceConfig[], CommandError>(__TAURI_INVOKE("list_calendar_sources")),
	addCalendarSource: (cfg: CalendarSourceConfig) => typedError<null, CommandError>(__TAURI_INVOKE("add_calendar_source", { cfg })),
	removeCalendarSource: (id: string) => typedError<null, CommandError>(__TAURI_INVOKE("remove_calendar_source", { id })),
	/**
	 *  Refresh a source's cached events. ICS-URL sources are fetched over HTTP;
	 *  Google/Outlook sources use stored OAuth tokens. Returns the number cached.
	 * 
	 *  `async` + `spawn_blocking`: the refresh does blocking network I/O (ICS
	 *  download or provider API round-trips), which would freeze the UI on the
	 *  main thread.
	 */
	refreshCalendarSource: (id: string) => typedError<number, CommandError>(__TAURI_INVOKE("refresh_calendar_source", { id })),
	/**  Import an `.ics` file (native picker), creating own events. Returns the count. */
	importIcs: () => typedError<number, CommandError>(__TAURI_INVOKE("import_ics")),
	/**  Export events in a range to an `.ics` file (save dialog). Returns saved path. */
	exportIcs: (rangeStart: string, rangeEnd: string) => typedError<string | null, CommandError>(__TAURI_INVOKE("export_ics", { rangeStart, rangeEnd })),
	/**
	 *  Run the interactive OAuth flow for `provider` ("google" | "outlook") and
	 *  register it as a calendar source.
	 * 
	 *  `async` + `spawn_blocking`: the flow blocks on the loopback listener for up
	 *  to 180s waiting for the browser redirect, then does the token exchange over
	 *  the network — on the main thread that would freeze the UI for the whole
	 *  flow. The engine lock is only taken afterwards, to register the source.
	 */
	oauthBegin: (provider: string) => typedError<null, CommandError>(__TAURI_INVOKE("oauth_begin", { provider })),
	/**  Whether a provider is currently connected. */
	oauthStatus: (provider: string) => __TAURI_INVOKE<boolean>("oauth_status", { provider }),
	/**  Disconnect a provider: clear tokens, its source, and its cached events. */
	oauthDisconnect: (provider: string) => typedError<null, CommandError>(__TAURI_INVOKE("oauth_disconnect", { provider })),
	listPlugins: () => typedError<PluginInfo[], CommandError>(__TAURI_INVOKE("list_plugins")),
	setPluginEnabled: (id: string, enabled: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("set_plugin_enabled", { id, enabled })),
	readPluginSource: (id: string) => typedError<string, CommandError>(__TAURI_INVOKE("read_plugin_source", { id })),
	/**  The actions the editor can offer (metadata only). */
	aiListActions: () => __TAURI_INVOKE<AiActionView[]>("ai_list_actions"),
	/**  All configured connections, each enriched with runtime status. */
	aiListConnections: () => typedError<AiConnectionView[], CommandError>(__TAURI_INVOKE("ai_list_connections")),
	/**  Create or update a connection; returns the refreshed list. */
	aiUpsertConnection: (config: AiConnectionConfig) => typedError<AiConnectionView[], CommandError>(__TAURI_INVOKE("ai_upsert_connection", { config })),
	/**  Delete a connection and forget its key; returns the refreshed list. */
	aiDeleteConnection: (id: string) => typedError<AiConnectionView[], CommandError>(__TAURI_INVOKE("ai_delete_connection", { id })),
	/**  Store (or, with a blank string, clear) a connection's API key. */
	aiSetApiKey: (id: string, key: string) => typedError<null, CommandError>(__TAURI_INVOKE("ai_set_api_key", { id, key })),
	/**  Clear a connection's API key. */
	aiClearApiKey: (id: string) => typedError<null, CommandError>(__TAURI_INVOKE("ai_clear_api_key", { id })),
	/**  Whether a key is stored for `id` (the key itself never leaves the backend). */
	aiHasApiKey: (id: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("ai_has_api_key", { id })),
	/**  Validate a connection's credentials without spending tokens. */
	aiTestConnection: (id: string) => typedError<null, CommandError>(__TAURI_INVOKE("ai_test_connection", { id })),
	/**
	 *  Start running an action. Returns a `request_id`; text streams back as
	 *  `ai-stream-chunk` events, ending with `ai-stream-done` or `ai-stream-error`.
	 */
	aiRunAction: (req: AiRunRequest) => typedError<string, CommandError>(__TAURI_INVOKE("ai_run_action", { req })),
	/**  Cancel an in-flight run (no-op if it already finished). */
	aiCancel: (requestId: string) => typedError<null, CommandError>(__TAURI_INVOKE("ai_cancel", { requestId })),
	/**  User-defined prompt templates: global (every vault) + the open vault's own. */
	aiListTemplates: () => typedError<AiTemplate[], CommandError>(__TAURI_INVOKE("ai_list_templates")),
	/**  Create or overwrite a prompt template in the chosen scope; returns the list. */
	aiSaveTemplate: (name: string, body: string, scope: AiTemplateScope) => typedError<AiTemplate[], CommandError>(__TAURI_INVOKE("ai_save_template", { name, body, scope })),
	/**  Delete a prompt template (by file id within its scope); returns the list. */
	aiDeleteTemplate: (id: string, scope: AiTemplateScope) => typedError<AiTemplate[], CommandError>(__TAURI_INVOKE("ai_delete_template", { id, scope })),
	/**  The current embedding config (which connection + model), if any. */
	aiEmbeddingConfig: () => typedError<{
	/**
	 *  Id of the OpenAI-compatible connection that provides base URL + API key,
	 *  or [`LOCAL_EMBEDDING_CONNECTION_ID`] to use the bundled on-device model.
	 */
	connectionId: string,
	/**
	 *  Embedding model id (e.g. `text-embedding-3-small`, `nomic-embed-text`).
	 *  Fixed to [`LOCAL_EMBEDDING_MODEL`] for the bundled model.
	 */
	model: string,
} | null, CommandError>(__TAURI_INVOKE("ai_embedding_config")),
	/**  Set the embedding config, or clear it when `connection_id` is blank. */
	aiSetEmbeddingConfig: (connectionId: string, model: string) => typedError<null, CommandError>(__TAURI_INVOKE("ai_set_embedding_config", { connectionId, model })),
	/**
	 *  Coverage of the semantic index for the settings panel (sync; counts only —
	 *  no network, no per-note file reads).
	 */
	aiEmbedStatus: () => typedError<EmbedStatus, CommandError>(__TAURI_INVOKE("ai_embed_status")),
	/**
	 *  (Re)build the semantic index: embed every note new or changed since its last
	 *  vector. Emits `ai-embed-progress` between batches and returns final coverage.
	 *  Network + file IO stay OFF the engine lock (mirrors `git_sync_now`): the only
	 *  times the lock is taken are short `.with()` bursts to snapshot, prune, and
	 *  upsert one batch.
	 */
	aiBuildEmbeddings: () => typedError<EmbedStatus, CommandError>(__TAURI_INVOKE("ai_build_embeddings")),
	/**
	 *  Notes semantically nearest to `path`, from stored embeddings only (local, no
	 *  network). Returns `aiEmbedStale` when the note isn't indexed for the current
	 *  model yet — or was edited since it was embedded — so the panel can nudge the
	 *  user to build the index instead of silently serving neighbors of old text.
	 */
	aiFindRelated: (path: string, limit: number) => typedError<RelatedNote[], CommandError>(__TAURI_INVOKE("ai_find_related", { path, limit })),
	/**
	 *  Answer a question from the vault. Runs hybrid retrieval (FTS keyword hits ∪
	 *  vector chunk hits, reciprocal-rank-fused — reusing [`index_search::search`]
	 *  and [`vectors::retrieve_related`]), returns the top-K passages as `citations`
	 *  up front, then streams a grounded answer over the shared `ai-stream-*` events
	 *  (keyed by the returned `request_id`, cancellable via [`ai_cancel`]). The
	 *  answer cites each claim as `[[n]]`, which the frontend resolves back to
	 *  `citations[n-1]`.
	 * 
	 *  Graceful degrade: with no embedding backend configured (or an index not yet
	 *  built), retrieval falls back to FTS-only. When retrieval finds nothing, the
	 *  model is **not** called — `request_id` is empty and the frontend shows the
	 *  honest "not in your notes" message rather than a hallucinated answer.
	 */
	aiRagAnswer: (connectionId: string, question: string) => typedError<RagResponse, CommandError>(__TAURI_INVOKE("ai_rag_answer", { connectionId, question })),
	/**
	 *  Extract entities from one note on demand: run the LLM action, parse + resolve
	 *  + dedupe the result, and upsert the entities and this note's mentions
	 *  (replacing any prior ones). Returns the note's resulting entity backlinks.
	 * 
	 *  Long-running (awaits the whole model reply), like `ai_build_embeddings`; all
	 *  network + file IO stay off the engine lock, which is taken only for short
	 *  snapshot/upsert bursts.
	 */
	entitiesExtractNote: (connectionId: string, path: string) => typedError<EntitySummary[], CommandError>(__TAURI_INVOKE("entities_extract_note", { connectionId, path })),
	/**
	 *  Every entity with at least one live mention, most-mentioned first — the
	 *  entities-panel list. Index-only, no network.
	 */
	entitiesList: () => typedError<EntitySummary[], CommandError>(__TAURI_INVOKE("entities_list")),
	/**  The entities a note mentions (its entity backlinks). Index-only. */
	entitiesForNote: (path: string) => typedError<EntitySummary[], CommandError>(__TAURI_INVOKE("entities_for_note", { path })),
	/**
	 *  All mentions of one entity across the vault — the "everything about X" view.
	 *  Index-only, no network.
	 */
	entitiesMentions: (entityId: number) => typedError<EntityMention[], CommandError>(__TAURI_INVOKE("entities_mentions", { entityId })),
};

/** Events */
export const events = {
	aiEmbedProgress: makeEvent<AiEmbedProgress>("ai-embed-progress"),
	aiStreamChunk: makeEvent<AiStreamChunk>("ai-stream-chunk"),
	aiStreamDone: makeEvent<AiStreamDone>("ai-stream-done"),
	aiStreamError: makeEvent<AiStreamError>("ai-stream-error"),
	conflictDetected: makeEvent<ConflictDetected>("conflict-detected"),
	gitConflictDetected: makeEvent<GitConflictDetected>("git-conflict-detected"),
	noteChanged: makeEvent<NoteChanged>("note-changed"),
	noteDeleted: makeEvent<NoteDeleted>("note-deleted"),
	reindexedEvent: makeEvent<ReindexedEvent>("reindexed-event"),
};

/* Types */
/**  A unified agenda entry merging tasks and calendar events. */
export type AgendaItem = {
	/**  `"task"` or `"event"`. */
	kind: string,
	title: string,
	/**  `YYYY-MM-DD` or `YYYY-MM-DDTHH:MM`. */
	start: string,
	allDay: boolean,
	source: string,
	/**  Task id or event id. */
	refId: string,
	/**  Source note path, if any. */
	notePath: string | null,
};

/**  Metadata describing one runnable action, surfaced to the editor picker. */
export type AiActionView = {
	id: string,
	/**  i18n key (namespace `ai`) for the display title. */
	titleKey: string,
	input: AiInputKind,
	scope: AiScope,
	insertMode: AiInsertMode,
};

/**
 *  Non-secret configuration for one connection. Persisted app-global in the
 *  desktop settings file. The matching API key (HTTP kinds) lives in the OS
 *  keychain under `ai:<id>` and is never stored here.
 */
export type AiConnectionConfig = {
	/**  Stable identifier (also the keychain account suffix). */
	id: string,
	kind: AiProviderKind,
	/**  Human-readable name shown in the picker. */
	label: string,
	/**
	 *  Base URL for OpenAI-compatible services (e.g. `https://api.deepseek.com`).
	 *  Optional for Anthropic (defaults to the public API) and unused for CLI.
	 */
	baseUrl?: string | null,
	/**  Model identifier sent to the provider / passed to the CLI `--model`. */
	model: string,
	enabled?: boolean,
	/**
	 *  CLI kinds only: run the agent INSIDE the vault with a curated file
	 *  toolset (open-ended edits) instead of the default sandboxed, no-tools
	 *  text generation in a temp dir. Opt-in and ignored for HTTP kinds. Every
	 *  agentic run is bracketed by a git checkpoint so it can be reverted.
	 */
	agentic?: boolean,
};

/**
 *  A connection enriched with runtime status for the frontend: whether it has a
 *  key (`configured`), whether the backend is reachable/installed (`available`),
 *  and the suggested model catalog.
 */
export type AiConnectionView = {
	id: string,
	kind: AiProviderKind,
	label: string,
	baseUrl: string | null,
	model: string,
	enabled: boolean,
	/**  Mirrors [`AiConnectionConfig::agentic`] (CLI kinds only). */
	agentic: boolean,
	/**  HTTP kinds: an API key is stored. CLI kinds: the binary is detected. */
	configured: boolean,
	/**  HTTP kinds: always true. CLI kinds: the binary is on PATH / configured. */
	available: boolean,
	models: AiModelInfo[],
};

/**  The note context an action runs against, sent from the editor. */
export type AiContext = {
	title?: string,
	markdown?: string,
	selection?: string | null,
};

/**
 *  Progress of a semantic-index build (`ai_build_embeddings`): notes embedded so
 *  far out of the total that need (re)embedding. Emitted between batches.
 */
export type AiEmbedProgress = {
	done: number,
	total: number,
};

/**
 *  Which connection + model produce note embeddings. References an existing
 *  [`AiConnectionConfig`] by id (so base URL + keychain key are not duplicated);
 *  the embedding `model` is separate because it differs from the chat model on
 *  the same endpoint. Persisted app-global in the desktop settings file; the
 *  referenced connection must be [`AiProviderKind::OpenAiCompatible`].
 */
export type AiEmbeddingConfig = {
	/**
	 *  Id of the OpenAI-compatible connection that provides base URL + API key,
	 *  or [`LOCAL_EMBEDDING_CONNECTION_ID`] to use the bundled on-device model.
	 */
	connectionId: string,
	/**
	 *  Embedding model id (e.g. `text-embedding-3-small`, `nomic-embed-text`).
	 *  Fixed to [`LOCAL_EMBEDDING_MODEL`] for the bundled model.
	 */
	model: string,
};

/**  Whether an action accepts a free-text user prompt in addition to the note. */
export type AiInputKind = 
/**  No extra input — the note is the whole task (e.g. summarize). */
"none" | 
/**  Optional extra instruction. */
"optional" | 
/**  A prompt is required (e.g. "write content from this brief"). */
"required";

/**
 *  The default way the result should be applied to the note. A hint for the
 *  frontend panel; the user can always override.
 */
export type AiInsertMode = 
/**  Show in the panel only; the user chooses what to do. */
"panelOnly" | 
/**  Insert at the cursor. */
"atCursor" | 
/**  Replace the current selection. */
"replaceSelection" | 
/**  Append to the end of the note. */
"append";

/**  A suggested model for a provider, shown in the settings dropdown. */
export type AiModelInfo = {
	id: string,
	label: string,
};

/**
 *  Which kind of backend a connection talks to. The HTTP kinds hit a remote
 *  API; the CLI kinds shell out to a locally-installed tool that uses the
 *  user's own login/subscription.
 */
export type AiProviderKind = 
/**  Anthropic Claude — `POST /v1/messages`. */
"anthropic" | 
/**
 *  OpenAI and any OpenAI-compatible service (DeepSeek, …) —
 *  `POST {base_url}/v1/chat/completions`. Distinguished only by `base_url`
 *  and `model`.
 */
"openAiCompatible" | 
/**  Locally-installed Claude Code (`claude`) CLI. (Adapter lands in Phase 2.) */
"claudeCli" | 
/**  Locally-installed OpenAI Codex (`codex`) CLI. (Adapter lands in Phase 2.) */
"codexCli";

/**  Input to `ai_run_action`. */
export type AiRunRequest = {
	connectionId: string,
	actionId: string,
	notePath?: string | null,
	context: AiContext,
	userInput?: string | null,
};

/**  Which slice of the note an action operates on. */
export type AiScope = "wholeNote" | "selection" | 
/**
 *  Prefer the selection, fall back to the whole note when nothing is
 *  selected.
 */
"selectionOrWholeNote";

/**  A chunk of AI-generated text for an in-flight request (keyed by `requestId`). */
export type AiStreamChunk = {
	requestId: string,
	delta: string,
};

/**  An AI request finished; carries token usage when the provider reported it. */
export type AiStreamDone = {
	requestId: string,
	usage: Usage | null,
};

/**  An AI request failed (transport, auth, or a provider error mid-stream). */
export type AiStreamError = {
	requestId: string,
	message: string,
};

/**
 *  A user-defined prompt template stored as a `.md` file. The file name is the
 *  display `name`; the file contents are the prompt `body`.
 */
export type AiTemplate = {
	/**  File name (with extension) — the identifier for delete (within a scope). */
	id: string,
	name: string,
	body: string,
	scope: AiTemplateScope,
};

/**  Where a prompt template is stored. */
export type AiTemplateScope = 
/**  App config dir — available in every vault on this machine. */
"global" | 
/**  `<vault>/.novalis/ai-prompts/` — synced with the vault via git. */
"vault";

/**  Basic app/build information surfaced to the UI. */
export type AppInfo = {
	name: string,
	version: string,
};

/**
 *  Appearance / theming. `theme` and `density` are applied at runtime by the
 *  frontend (CSS variables / `data-*` on the document element); `accent` is a
 *  color token shared with the folder-color palette.
 */
export type AppearancePrefs = {
	/**  `"dark"` | `"light"` | `"system"`. */
	theme?: string,
	/**  Accent color token (e.g. `"indigo"`), shared with the folder palette. */
	accent?: string,
	/**  Base UI font size in px. */
	fontSize?: number,
	/**  `"comfortable"` | `"compact"`. */
	density?: string,
};

/**
 *  One indexed block (a line tagged with a stable ` ^id` marker) surfaced to the
 *  `((` reference autocomplete. `text` has the marker stripped.
 */
export type BlockHit = {
	id: string,
	notePath: string,
	noteTitle: string,
	text: string,
};

/**
 *  The resolution of a `((^id))` block reference. `notePath`/`noteTitle`/`text`
 *  are set when `found`; all `None`/`false` for a dangling id (its block was
 *  deleted). Unlike `[[wikilinks]]`, a block reference never materializes
 *  anything on a miss — a broken reference simply renders as "missing".
 */
export type BlockResolution = {
	found: boolean,
	notePath: string | null,
	noteTitle: string | null,
	text: string | null,
};

/**
 *  A calendar event — either an own event (backed by a markdown note in the
 *  vault) or a cached event from a remote source. Times are strings:
 *  `YYYY-MM-DD` for all-day, or `YYYY-MM-DDTHH:MM` for timed.
 */
export type CalendarEvent = {
	id: string,
	/**  `"local"` for vault events, otherwise the calendar source id. */
	sourceId: string,
	title: string,
	start: string,
	end: string | null,
	allDay: boolean,
	/**  RFC 5545 RRULE string (without the `RRULE:` prefix), if recurring. */
	rrule: string | null,
	location: string | null,
	/**  Vault-relative note path for own events. */
	notePath: string | null,
	/**
	 *  Attendee display names (own events: from note frontmatter; remote:
	 *  parsed from Google/MS payloads). Empty when none are known. NOTE: the
	 *  `events` index has no attendees column, so remote attendees are dropped
	 *  on cache — only own-event (frontmatter) attendees survive a reload.
	 */
	attendees?: string[],
};

/**  Calendar display preferences. */
export type CalendarPrefs = {
	/**  `"monday"` | `"sunday"`. */
	weekStart?: string,
	/**  Default duration (minutes) for a newly created event. */
	defaultEventMinutes?: number,
	/**  `"24h"` | `"12h"`. */
	timeFormat?: string,
};

/**
 *  A configured calendar source (subscription). `kind` is `"icsUrl"`,
 *  `"google"`, or `"outlook"`. Remote events are cached locally under its id.
 */
export type CalendarSourceConfig = {
	id: string,
	kind: string,
	name: string,
	url: string | null,
	enabled?: boolean,
};

/**  A `.canvas` file discovered in the vault. */
export type CanvasFile = {
	/**  Vault-relative, forward-slashed path (e.g. `boards/plan.canvas`). */
	path: string,
	/**  Display name — the file stem, without the `.canvas` extension. */
	name: string,
};

export type CaptureRequest = {
	text: string,
	/**  When true the line is captured as a task checkbox; otherwise a bullet. */
	asTask?: boolean,
	notePath: string | null,
};

/**
 *  Serializable error returned to the frontend. `kind` lets the UI branch
 *  (e.g. show an "open a vault" prompt for `noVault`).
 */
export type CommandError = {
	kind: string,
	message: string,
};

/**  A sync-conflict file was detected. */
export type ConflictDetected = {
	path: string,
};

export type ConflictDiff = {
	originalPath: string,
	conflictPath: string,
	originalContent: string,
	conflictContent: string,
	originalExists: boolean,
};

/**  A sync-conflict file detected in the vault (e.g. OneDrive `note (1).md`). */
export type ConflictFile = {
	id: string,
	originalPath: string,
	conflictPath: string,
	detectedAt: string,
};

export type CreateNoteRequest = {
	path: string,
	content: string | null,
	template: string | null,
};

export type CreateTaskRequest = {
	text: string,
	status: string | null,
	priority: string | null,
	dueDate: string | null,
	/**  Explicit destination note (overrides the preference-based strategy). */
	notePath: string | null,
};

/**  One line of a unified line-diff between a snapshot and the current note. */
export type DiffLine = {
	/**  `"equal"`, `"insert"`, or `"delete"`. */
	kind: string,
	content: string,
};

/**  Editor behavior. Debounce values are milliseconds. */
export type EditorPrefs = {
	/**  Autosave debounce after the last keystroke. */
	autosaveMs?: number,
	/**  Internal serialize/typing-responsiveness debounce (advanced). */
	serializeMs?: number,
	/**  Browser spellcheck in the editor. */
	spellcheck?: boolean,
	/**  Open notes in reading mode (rendered, non-editable) by default. */
	defaultReadingMode?: boolean,
	/**
	 *  Ambient AI suggestions: after an edit settles, compute link/tag
	 *  suggestions in the background when a provider is configured. Off by
	 *  default — the background calls cost tokens, so it is explicit opt-in.
	 */
	ambientAi?: boolean,
};

/**
 *  The resolution of an `![[embed]]` reference. `path`/`title`/`body` are set
 *  for a `Note` hit (`body` has the frontmatter stripped); all `None` for a
 *  `Missing` target. `Image` is classified frontend-side by extension, so the
 *  backend only ever returns `Note` or `Missing`.
 */
export type EmbedResolution = {
	kind: EmbedTargetKind,
	path: string | null,
	title: string | null,
	body: string | null,
};

/**  Coverage of the semantic index, for the settings panel. Carries no secret. */
export type EmbedStatus = {
	/**  A valid, enabled OpenAI-compatible embedding connection is configured. */
	configured: boolean,
	/**  The configured embedding model, when `configured`. */
	model: string | null,
	/**  Notes eligible to embed (local, non-placeholder). */
	total: number,
	/**  Notes that currently have a vector for the configured model. */
	embedded: number,
};

/**
 *  What an `![[embed]]` target resolved to. A note renders its body inline; an
 *  image renders via the host's `resolveImageSrc`; a miss reports `Missing` so
 *  the UI can offer a "create note" affordance — unlike `[[wikilinks]]`, embeds
 *  never materialize a note on miss.
 */
export type EmbedTargetKind = "note" | "image" | "missing";

/**
 *  What kind of thing an extracted entity is. The `extract-entities` action asks
 *  the model for exactly one of these strings; an unknown/missing value maps to
 *  [`EntityKind::Other`] rather than dropping the entity. Serializes lowercase
 *  (`person`, `project`, …), matching the STRICT-JSON `kind` field the model
 *  returns and the value stored in `entities.kind`.
 */
export type EntityKind = "person" | "project" | "org" | "place" | "other";

/**
 *  One mention of an entity in a note — a row of the "everything about X" view.
 *  The `snippet` is a passage of the note around the mention (the surrounding
 *  context), with `char_start`/`char_end` its offsets into the note body; when
 *  the entity was inferred rather than found literally, the snippet is empty and
 *  the offsets are `0..0`.
 */
export type EntityMention = {
	notePath: string,
	noteTitle: string,
	/**  The surface form that matched in the note (the entity name or an alias). */
	surface: string,
	snippet: string,
	charStart: number,
	charEnd: number,
};

/**
 *  One entity in the local entity graph, with its live mention count — the row
 *  the entities panel lists. `id` is the store's autoincrement key (rendered as
 *  a JS number via the global bigint cast); `aliases` are the alternative
 *  surface forms merged into this entity.
 */
export type EntitySummary = {
	id: number,
	name: string,
	kind: EntityKind,
	/**  Case-folded, whitespace-collapsed key the entity is deduped by. */
	canonicalName: string,
	aliases: string[],
	/**  Notes that mention this entity (counting only notes still in the index). */
	mentionCount: number,
};

/**  Request to create/update an own event (written to a markdown note). */
export type EventInput = {
	title: string,
	/**  `YYYY-MM-DD`. */
	date: string,
	allDay: boolean,
	/**  `HH:MM` when not all-day. */
	startTime: string | null,
	endTime: string | null,
	rrule: string | null,
	location: string | null,
	/**  Existing note path when updating; `None` to create a new event note. */
	notePath: string | null,
	/**  Attendee display names, persisted to the note's frontmatter. */
	attendees?: string[],
};

export type FileTreePrefs = {
	/**  `"name"` | `"modified"` | `"created"` | `"manual"`. */
	sortBy?: string,
	sortDir?: string,
	/**
	 *  Folder path (vault-relative, forward-slashed) -> color token (e.g. "indigo").
	 *  Synced with the vault so colors follow it across devices.
	 */
	folderColors?: { [key in string]: string },
	/**
	 *  Parent path ("" = vault root) -> ordered child item keys (folder paths and
	 *  note paths, interleaved). Used when `sort_by == "manual"`. Keys never
	 *  collide because notes end in `.md`.
	 */
	itemOrder?: { [key in string]: string[] },
};

/**  A node in the recursive vault folder tree. */
export type FolderNode = {
	name: string,
	path: string,
	children: FolderNode[],
	notes: NoteSummary[],
};

/**
 *  The whole-vault link graph: every indexed note plus every resolved
 *  `[[link]]` edge between two existing notes.
 */
export type FullGraph = {
	nodes: VaultGraphNode[],
	edges: GraphEdge[],
};

/**  General / startup behavior. */
export type GeneralPrefs = {
	/**  View shown on launch: `"notes"` | `"tasks"` | `"calendar"`. */
	defaultAppView?: string,
};

/**  One commit, as surfaced in the Sync settings panel. */
export type GitCommitInfo = {
	/**  Full commit id (hex); the UI shortens it for display. */
	id: string,
	/**  First line of the commit message. */
	message: string,
	/**  Commit time, RFC 3339 in UTC. */
	time: string,
};

/**
 *  One conflicted path of a diverged merge (P3a), all three sides
 *  materialized from their blob OIDs. `None` = that side has no entry — the
 *  delete-vs-edit case. Content is capped like the OneDrive conflict
 *  preview: oversized or non-UTF-8 (binary) blobs are replaced by a
 *  bracketed placeholder rather than failing — resolving by "ours"/"theirs"
 *  stays lossless regardless, because finalization re-reads the blob OID,
 *  never this preview text.
 */
export type GitConflict = {
	/**  Vault-relative path (forward-slashed). */
	path: string,
	/**  Content at the merge base (common ancestor). */
	base: string | null,
	/**  Content on the local branch tip. */
	ours: string | null,
	/**  Content on the remote-tracking tip. */
	theirs: string | null,
};

/**
 *  A background sync cycle hit merge conflicts (P3b). Emitted by the
 *  auto-committer only when the conflict set CHANGES — a persisting identical
 *  conflict is re-detected every interval but must not re-open the resolver
 *  on every tick. `paths` are vault-relative, sorted.
 */
export type GitConflictDetected = {
	paths: string[],
};

/**
 *  Local git versioning (Git sync P1 — no remotes yet). Synced with the vault
 *  like every block here, so enabling follows the vault across devices.
 */
export type GitPrefs = {
	enabled?: boolean,
	/**
	 *  Commit author identity — always explicit, never read from the user's
	 *  global git config (a machine without one must behave the same).
	 */
	authorName?: string,
	authorEmail?: string,
	/**
	 *  Auto-commit interval in seconds; the background committer also
	 *  enforces a 30s floor.
	 */
	autoCommitSecs?: number,
};

/**  The user's decision for one conflicted path of a diverged merge. */
export type GitResolution = {
	/**  Vault-relative path (forward-slashed), as reported by `GitConflict`. */
	path: string,
	resolution: GitResolutionChoice,
};

/**
 *  Externally tagged like [`GitSyncKind`]: `"ours"`/`"theirs"` cross IPC as
 *  plain strings, manual content as `{ manual: { content } }`. Choosing a
 *  side whose entry is absent (delete-vs-edit) resolves to the deletion.
 */
export type GitResolutionChoice = 
/**  Keep the local branch's version (or its deletion). */
"ours" | 
/**  Keep the remote's version (or its deletion). */
"theirs" | 
/**  Replace the file with hand-merged content. */
{ manual: {
	content: string,
} };

/**  Local repository state of the open vault. */
export type GitStatus = {
	/**  Whether the vault root is a git repository. */
	initialized: boolean,
	/**
	 *  Working-tree paths differing from HEAD (untracked + modified +
	 *  deleted), with `.gitignore` respected.
	 */
	dirty: number,
	/**  HEAD branch shorthand (`main` for repos Novalis created). */
	branch: string | null,
	lastCommit: GitCommitInfo | null,
	/**
	 *  URL of the `origin` remote (the repo's git config is the single
	 *  source of truth — not duplicated into prefs).
	 */
	remoteUrl: string | null,
	/**
	 *  Local commits the remote tracking ref doesn't have. Computed from
	 *  local refs only (no network) — current as of the last fetch.
	 */
	ahead: number,
	/**
	 *  Remote-tracking commits the local branch doesn't have (as of the
	 *  last fetch).
	 */
	behind: number,
};

/**
 *  Externally tagged (serde default): unit variants cross IPC as plain
 *  strings (`"upToDate"`), the data-carrying [`GitSyncKind::Conflicted`]
 *  as `{ conflicted: { paths } }` — the TS side narrows on
 *  `typeof kind === "string"`.
 */
export type GitSyncKind = 
/**  Nothing to transfer in either direction. */
"upToDate" | 
/**  Local commits were pushed. */
"pushed" | 
/**
 *  The local branch fast-forwarded onto the remote (incl. first
 *  adoption of a populated remote into a fresh vault).
 */
"pulled" | 
/**
 *  Diverged histories were reconciled by an automatic 3-way merge
 *  commit (P2b), checked out locally and pushed.
 */
"merged" | 
/**
 *  Both sides have new commits but the auto-merge was not attempted
 *  (the repository is busy with a user operation, e.g. mid-merge in
 *  an adopted repo).
 */
"diverged" | 
/**
 *  The automatic merge found conflicting edits. Detection ran
 *  entirely in memory — the working tree and repository state are
 *  untouched. `paths` lists the affected vault-relative files
 *  (sorted; a side deleted here and edited there still yields its
 *  path). Resolution UI is P3.
 */
{ conflicted: {
	paths: string[],
} } | 
/**  No `origin` remote is configured. */
"noRemote";

/**
 *  What one sync cycle did (P2b: fast-forward, push, or an automatic
 *  3-way merge — conflicts stop the cycle and are surfaced; Novalis never
 *  force-pushes).
 */
export type GitSyncOutcome = {
	kind: GitSyncKind,
	/**  Local commits the remote was missing at decision time. */
	ahead: number,
	/**  Remote commits the local branch was missing at decision time. */
	behind: number,
};

/**  A directed `[[link]]` edge between two notes, by path. */
export type GraphEdge = {
	source: string,
	target: string,
};

/**  A node (note) in the local link graph. */
export type GraphNode = {
	path: string,
	title: string,
};

export type KanbanColumnDef = {
	id?: string,
	title?: string,
};

/**
 *  One matching line within a note that links to or mentions a target title.
 *  `line` is 1-based and refers to the raw file (frontmatter included), so it
 *  can locate the line again for [`crate::notes::link_mention`].
 */
export type LinkMatch = {
	line: number,
	snippet: string,
};

/**
 *  A note that references a target title, grouped with the lines where it does.
 *  Used for the "linked references" and "unlinked mentions" panels.
 */
export type LinkReference = {
	path: string,
	title: string,
	folder: string,
	modified: string,
	matches: LinkMatch[],
};

/**
 *  Result of materializing a meeting note ([`crate::calendar::add_meeting_note`]):
 *  the day's journal note plus every attendee note that was created or linked.
 */
export type MeetingNoteResult = {
	/**  Vault-relative path of the journal note the entry was appended to. */
	journalPath: string,
	/**  Vault-relative paths of the attendee notes (created or resolved). */
	attendeeNotes: string[],
};

/**  A full note: raw markdown `content` (frontmatter included) plus a parsed view. */
export type Note = {
	path: string,
	title: string,
	content: string,
	frontmatter: NoteFrontmatter,
	wordCount: number,
	/**
	 *  Typed view of the custom frontmatter keys (the `extra` passthrough),
	 *  in the alphabetical order serde_yaml re-emits them. Derived on read —
	 *  the YAML stays the source of truth.
	 */
	properties?: NotePropertyEntry[],
};

/**  A note was created or modified on disk (path is vault-relative). */
export type NoteChanged = {
	path: string,
};

/**  A note was removed from disk. */
export type NoteDeleted = {
	path: string,
};

/**
 *  YAML frontmatter. Field names are the literal YAML keys (no camelCase). The
 *  `extra` map preserves any unknown keys verbatim so we never drop a user's
 *  metadata on round-trip; it's skipped from the TS type as it is open-ended.
 */
export type NoteFrontmatter = {
	title?: string | null,
	tags?: string[],
	aliases?: string[],
	created?: string,
	modified?: string,
	pinned?: boolean,
};

/**
 *  The 1-hop link neighborhood of a note: the note itself (`center`), the notes
 *  it links to, and the notes that link to it.
 */
export type NoteGraph = {
	center: string,
	nodes: GraphNode[],
	edges: GraphEdge[],
};

/**  One custom frontmatter key/value pair, surfaced on [`Note`]. */
export type NotePropertyEntry = {
	key: string,
	value: PropertyValue,
};

/**
 *  A note's typed relations in both directions. `outgoing` are the notes this
 *  note's frontmatter points to; `incoming` are the notes whose frontmatter
 *  points here — the reciprocal side, derived from the same `note_relations`
 *  rows (one forward row per relation serves both queries).
 */
export type NoteRelations = {
	outgoing: RelationRef[],
	incoming: RelationRef[],
};

/**  Lightweight note metadata used for lists, the file tree, and search results. */
export type NoteSummary = {
	path: string,
	title: string,
	folder: string,
	tags: string[],
	aliases?: string[],
	created: string,
	modified: string,
	pinned: boolean,
	wordCount: number,
	taskTotal: number,
	taskCompleted: number,
	/**
	 *  True for an "online only" cloud placeholder (OneDrive/iCloud) whose
	 *  content isn't on disk yet, so opening it triggers a network download.
	 */
	cloudOnly: boolean,
};

export type NoteTemplate = {
	id: string,
	name: string,
	description: string,
	content: string,
	created: string,
};

/**  A discovered plugin plus whether it is enabled. */
export type PluginInfo = {
	manifest: PluginManifest,
	enabled: boolean,
};

/**
 *  A plugin's `plugin.json` manifest. Plugins live in
 *  `<vault>/.novalis/plugins/<id>/` and run sandboxed in the frontend.
 */
export type PluginManifest = {
	id: string,
	name: string,
	version?: string,
	description?: string,
	entry?: string,
	/**
	 *  Capabilities the plugin may use, e.g. `["notes:read", "notes:write",
	 *  "tasks:read", "search", "notify"]`. The host enforces these.
	 */
	capabilities?: string[],
};

export type Preferences = {
	taskView?: TaskViewPrefs,
	fileTree?: FileTreePrefs,
	appearance?: AppearancePrefs,
	editor?: EditorPrefs,
	calendar?: CalendarPrefs,
	general?: GeneralPrefs,
	git?: GitPrefs,
	/**
	 *  User-named saved queries for the query view. A preference (JSON), synced
	 *  with the vault like every block here — never a DB table.
	 */
	savedQueries?: SavedQuery[],
};

/**
 *  The typed value of one custom frontmatter property — a closed wire enum
 *  over the YAML shapes the properties panel can edit. Anything else a user
 *  hand-wrote (nested maps, mixed-type arrays, integers beyond f64's exact
 *  range) is surfaced as `Text` by the read mapper and only overwritten by an
 *  explicit edit.
 * 
 *  `Number` is `Option` because JSON cannot carry NaN/Infinity — a frontend
 *  `NaN` arrives over IPC as `null`, and it must surface as a structured
 *  `BadRequest` from the write boundary rather than an opaque deserialization
 *  failure. The read mapper never produces `None`.
 */
export type PropertyValue = { kind: "text"; value: string } | { kind: "number"; value: number | null } | { kind: "checkbox"; value: boolean } | { kind: "list"; value: string[] };

/**
 *  One matched note in a query result. Carries the metadata a table view needs
 *  plus the typed frontmatter properties (so property columns render without a
 *  second round-trip) and a best-guess `date` for calendar placement.
 */
export type QueryNoteRow = {
	path: string,
	title: string,
	folder: string,
	modified: string,
	created: string,
	tags: string[],
	/**  Typed frontmatter properties, in stored order — the extra table columns. */
	properties: NotePropertyEntry[],
	/**
	 *  The note's date for the calendar view (`date`/`due`/`start` frontmatter,
	 *  whichever resolves first), or `None` when the note isn't dated.
	 */
	date: string | null,
};

/**
 *  The result of running a query: matched notes, the tasks belonging to those
 *  notes (populated only when the query touches tasks), the suggested view, and
 *  the union of property keys present across the rows (the table's dynamic
 *  columns, in first-seen order).
 */
export type QueryResult = {
	notes: QueryNoteRow[],
	tasks: Task[],
	view: QueryViewKind,
	propertyKeys: string[],
	/**
	 *  True when at least one matched note is dated — lets the UI offer the
	 *  calendar view even for a query that didn't explicitly request it.
	 */
	hasDates: boolean,
};

/**
 *  Which result view the query engine suggests (or the query explicitly asked
 *  for). The frontend can override, but this is the sensible default: a query
 *  touching tasks defaults to `Kanban`, one whose notes carry dates can offer
 *  `Calendar`, everything else renders as a `Table`.
 */
export type QueryViewKind = "table" | "kanban" | "calendar";

/**
 *  One retrieved passage backing a "chat with your vault" answer. The model
 *  cites it as `[[id]]` (see [`crate::ai::rag::format_citation`]); the frontend
 *  resolves that token back to this note + character span to make the citation
 *  clickable. `snippet` is the passage text — both shown as a preview and fed to
 *  the model as grounding.
 */
export type RagCitation = {
	/**  1-based passage number, matching the `[[id]]` token in the answer. */
	id: number,
	path: string,
	title: string,
	/**
	 *  Character offsets of the passage into the note's embed text (title+body).
	 *  `0..0` for a keyword-only (FTS) hit that carries no precise chunk span.
	 */
	charStart: number,
	charEnd: number,
	/**  The passage text (also the grounding sent to the model). */
	snippet: string,
};

/**
 *  Result of starting a RAG answer: the retrieved citations (returned up front
 *  so the panel can render them immediately) plus the streaming `request_id`
 *  whose answer text arrives over the shared `ai-stream-*` events and is
 *  cancellable via `ai_cancel`. `request_id` is **empty** when retrieval found
 *  nothing — the backend never calls the model, and the frontend shows the
 *  honest "not in your notes" message instead of a hallucinated answer.
 */
export type RagResponse = {
	requestId: string,
	citations: RagCitation[],
};

/**  An entry in the recent-vaults list (most-recent first in the stored list). */
export type RecentVault = {
	/**  Absolute path to the vault folder. */
	path: string,
	/**  Epoch milliseconds of the last time this vault was opened. */
	lastOpened: number,
};

/**  Emitted when the vault finishes (re)indexing, so the UI can refresh fully. */
export type ReindexedEvent = null;

/**  A semantically related note returned by "find related" / semantic search. */
export type RelatedNote = {
	path: string,
	title: string,
	/**  Cosine similarity in `[-1, 1]` (typically `[0, 1]` for text embeddings). */
	score: number | null,
};

/**
 *  One end of a typed relation between two notes, as seen from the other note:
 *  the note at `path`/`title`, reached via the property `key` that declared the
 *  relation. Used for both the outgoing and (reciprocal) incoming directions.
 */
export type RelationRef = {
	path: string,
	title: string,
	key: string,
};

export type ResolveConflictRequest = {
	/**  "original" | "conflict" | "both" */
	keep: string,
	/**  Vault-relative path to the original file (authoritative copy). */
	originalPath: string,
	/**  Vault-relative path to the conflict file as reported by list_conflicts. */
	conflictPath: string,
};

/**
 *  The assembled weekly-review digest. `range_start`/`range_end` are the
 *  *inclusive* local dates of the window (for display); `markdown` is the
 *  ready-to-insert section rendered from the buckets.
 */
export type ReviewDigest = {
	/**  Inclusive window start, local date `YYYY-MM-DD`. */
	rangeStart: string,
	/**  Inclusive window end, local date `YYYY-MM-DD`. */
	rangeEnd: string,
	/**  Tasks completed with an effective date in the window (see module docs). */
	completed: Task[],
	/**  Open tasks whose `@due` is before the window start (slipped). */
	overdue: Task[],
	/**  Open tasks whose `@due` is within the window. */
	dueThisWeek: Task[],
	/**  Notes whose `modified` instant falls within the window. */
	notesTouched: NoteSummary[],
	/**  Scheduled tasks + calendar events over the window. */
	agenda: AgendaItem[],
	/**  Canonical markdown section, ready to insert into a note. */
	markdown: string,
};

/**
 *  A numeric aggregation over the notes a relation points to. The
 *  data-layer primitive a future query engine's "rollup" columns build on.
 */
export type RollupOp = "count" | "sum" | "avg" | "min" | "max";

/**
 *  The result of a rollup: `count` is how many related notes contributed a
 *  numeric value; `value` is the aggregate, or `None` when it is undefined
 *  (`Avg`/`Min`/`Max` over an empty set). `Count`/`Sum` are always defined.
 */
export type RollupResult = {
	op: RollupOp,
	count: number,
	value: number | null,
};

/**  A user-named saved query, persisted as a preference (JSON), never a DB row. */
export type SavedQuery = {
	name: string,
	/**  The raw DSL string, re-parsed on run (the source of truth, not the AST). */
	query: string,
};

/**  A full-text search hit with an FTS5 snippet and rank-derived score. */
export type SearchResult = {
	path: string,
	title: string,
	snippet: string,
	score: number | null,
};

/**
 *  A distinct note tag with the number of notes carrying it. Powers the tag
 *  browser and `#tag` autocomplete.
 */
export type TagCount = {
	tag: string,
	count: number,
};

/**
 *  A task extracted from a markdown checkbox line, e.g.
 *  `- [ ] Buy milk @due(2026-05-30) @priority(high) @status(todo) #shopping`.
 */
export type Task = {
	id: string,
	text: string,
	completed: boolean,
	priority: string | null,
	dueDate: string | null,
	/**  `@start(YYYY-MM-DD)` — the scheduled "do" date (distinct from due). */
	startDate?: string | null,
	/**  `@remind(YYYY-MM-DDTHH:MM)` — an absolute (local) reminder datetime. */
	remind?: string | null,
	status: string | null,
	sourceNote: string,
	sourceLine: number,
	tags: string[],
	repeat?: string | null,
	parentId?: string | null,
	/**
	 *  The source note's display title (frontmatter / first H1 / filename),
	 *  derived consistently with the search index — for board cards/lanes.
	 */
	noteTitle?: string,
	/**  The nearest preceding markdown heading (the task's section), if any. */
	heading?: string | null,
	/**  `@project(slug)` annotation — the task's project bucket. */
	project?: string | null,
	/**  `@epic(slug)` annotation. */
	epic?: string | null,
};

export type TaskCreationPrefs = {
	strategy?: string,
	inboxPath?: string,
};

/**  Filters for [`crate::tasks::service::list`]. */
export type TaskQuery = {
	/**  "open" | "completed" | "all" */
	status: string | null,
	priority: string | null,
	dueBefore: string | null,
	dueAfter: string | null,
	note: string | null,
	folder: string | null,
};

export type TaskViewPrefs = {
	defaultMode?: string,
	kanbanColumns?: KanbanColumnDef[],
	taskCreation?: TaskCreationPrefs,
	/**
	 *  Project slug -> color token (e.g. "indigo"), mirroring
	 *  [`FileTreePrefs::folder_colors`]. Synced with the vault.
	 */
	projectColors?: { [key in string]: string },
};

export type TrashItem = {
	id: string,
	originalPath: string,
	trashedAt: string,
	filename: string,
};

export type UpdateMetaRequest = {
	path: string | null,
	title: string | null,
	tags: string[] | null,
	pinned: boolean | null,
	aliases: string[] | null,
};

/**  Token usage reported by a provider when available. */
export type Usage = {
	inputTokens?: number | null,
	outputTokens?: number | null,
};

/**
 *  A node in the whole-vault graph. A parallel type (not a widened
 *  [`GraphNode`], which `note_graph` still serves) — the vault view colors
 *  nodes by folder, so it carries one extra field.
 */
export type VaultGraphNode = {
	path: string,
	title: string,
	folder: string,
};

export type VaultInfo = {
	path: string,
	noteCount: number,
	folderCount: number,
	totalWords: number,
	totalTasks: number,
	completedTasks: number,
};

/**  Aggregate vault statistics, including a tag histogram. */
export type VaultStats = {
	noteCount: number,
	wordCount: number,
	taskTotal: number,
	taskCompleted: number,
	tagDistribution: { [key in string]: number },
};

/**  Metadata for one stored snapshot of a note. */
export type VersionMeta = {
	/**  Snapshot id = its timestamped filename stem (`YYYYMMDD_HHMMSS_mmm`). */
	id: string,
	/**  When the snapshot was taken (RFC 3339, derived from the id). */
	createdAt: string,
	/**  Byte size of the snapshot content. */
	size: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

