#!/bin/sh
# Re-apply Novalis's hand-edited Android native sources into the generated
# project. `apps/desktop/src-tauri/gen/` is git-ignored (regenerated by
# `tauri android init`), so any native customization must be copied back in
# after init and before a build. Run this after `pnpm android:init`, or
# whenever gen/android was regenerated. Idempotent.
#
# Overrides (source of truth under apps/desktop/android/):
#   MainActivity.kt — injects real edge-to-edge insets as CSS vars (see MOBILE.md)

set -e
here="$(cd "$(dirname "$0")/.." && pwd)"
src="$here/apps/desktop/android"
gen="$here/apps/desktop/src-tauri/gen/android"

if [ ! -d "$gen" ]; then
  echo "android-overrides: $gen missing — run 'pnpm --dir apps/desktop android:init' first" >&2
  exit 1
fi

dst="$gen/app/src/main/java/com/novalis/desktop/MainActivity.kt"
cp "$src/MainActivity.kt" "$dst"
echo "android-overrides: applied MainActivity.kt"
